apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prjctr
  template:
    metadata:
      name: dummy-pod
      labels:
        app: prjctr
    spec:
      containers:
      - name: dummy-pod
        image: dmtlevin/prjctr:latest
        ports:
        - containerPort: 8000
          name: http-web-svc