apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  labels:
    app: prjctr
spec:
  containers:
  - name: prjctr
    image: dmtlevin/prjctr:latest
    ports:
    - containerPort: 8000
      name: http-web-svc