apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  type: NodePort
  selector:
    app: prjctr
  ports:
  - name: main-port
    port: 8000
    nodePort: 30000
    targetPort: http-web-svc